name: crisis_response_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_storage: ^13.0.6

  # Permissions & device info
  permission_handler: ^11.3.1
  device_info_plus: ^12.3.0

  # Sensors, connectivity, and utilities
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  sensors_plus: ^7.0.0
  connectivity_plus: ^7.0.0
  battery_plus: ^7.0.0
  vibration: ^3.1.5
  shared_preferences: ^2.5.4
  crypto: ^3.0.7
  intl: ^0.20.2
  timezone: ^0.9.0

  # Media & storage
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  camera: ^0.11.3
  audioplayers: ^5.0.0

  # Notifications
  flutter_local_notifications: ^17.2.1
  telephony: ^0.2.0

  # UI & utilities
  url_launcher: ^6.3.2
  flutter_blue_plus: ^2.1.0
  share_plus: ^12.0.1
  qr_flutter: ^4.1.0
  pdf: ^3.11.3
  cached_network_image: ^3.4.1
  hive_flutter: ^1.1.0
  provider: ^6.1.5+1
  google_maps_flutter: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Example for assets (optional)
  # assets:
  #   - images/
